services:
  financial-app:
    container_name: financial-app-container
    build: ./financial.app
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - smart-finance-network



  database:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: shared_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - smart-finance-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  smart-finance-network:
    driver: bridge

volumes:
  db_data:
