spring:
  datasource:
    url: jdbc:h2:mem:financial_db_dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update # Crea o actualiza automáticamente las tablas
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console # URL para acceder a la consola H2

# Logging más detallado en dev
logging:
  level:
    org.hibernate.SQL: DEBUG
